// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf1AhTn2NAOru6jzZT9V72uOwb-aItrM8',
    appId: '1:527504144105:web:d92cf692742c99fa43e278',
    messagingSenderId: '527504144105',
    projectId: 'chatapp-ae799',
    authDomain: 'chatapp-ae799.firebaseapp.com',
    databaseURL: 'https://chatapp-ae799.firebaseio.com',
    storageBucket: 'chatapp-ae799.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9pvuHYJ8w6Yr03JfEiKy8Zi65TpuXT9c',
    appId: '1:527504144105:android:6e28db96b3d84ee543e278',
    messagingSenderId: '527504144105',
    projectId: 'chatapp-ae799',
    databaseURL: 'https://chatapp-ae799.firebaseio.com',
    storageBucket: 'chatapp-ae799.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw12lgxWuNSyzY5WL0pCQ5GAX0CtV6muU',
    appId: '1:527504144105:ios:d4a373060315eb9b43e278',
    messagingSenderId: '527504144105',
    projectId: 'chatapp-ae799',
    databaseURL: 'https://chatapp-ae799.firebaseio.com',
    storageBucket: 'chatapp-ae799.appspot.com',
    androidClientId: '527504144105-4kpkdcjnqj0a3ina40hgen6sdjajuko2.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw12lgxWuNSyzY5WL0pCQ5GAX0CtV6muU',
    appId: '1:527504144105:ios:c398556e558b940143e278',
    messagingSenderId: '527504144105',
    projectId: 'chatapp-ae799',
    databaseURL: 'https://chatapp-ae799.firebaseio.com',
    storageBucket: 'chatapp-ae799.appspot.com',
    androidClientId: '527504144105-4kpkdcjnqj0a3ina40hgen6sdjajuko2.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppFlutter.RunnerTests',
  );
}
